apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: test-namespace
spec:
  selector:
    app: fastapi-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000